function rating_types = call_ratingtypes_caps
%call_ratingtypes
%This function can call dictionary of rating types and prompts.
%its output is rating_types, and it has 2 fields.
%rating_types.alltypes : dictionary of rating types
%rating_types.prompts : prompts for each rating type

global basedir subjID subjnum runtype

ts_dir = fullfile(basedir, 'trial_sequence');
ts_fname = filenames(fullfile(ts_dir, ['trial_sequence*' subjID '*.mat']), 'char');
load(ts_fname);
my_music_dir = filenames(fullfile(basedir, '/subj_music', ['MIA', num2str(subjnum, '%.3d')]), 'char');

music_list_xlsx = fullfile(my_music_dir, 'MIA_music_list.xlsx');
music_list = readtable(music_list_xlsx, 'Sheet', 'List');
music_all.list = music_list.List;

if ismember(runtype, {'REST1', 'TEST1', 'MUSIC1', 'CAPS1', 'CAPS2'})
    switch runtype
        case 'REST1' % to block the error
            data.music_order = ts.run_music_order(1,:);
        case 'TEST1' % to block the error
            data.music_order = ts.run_music_order(1,:);
        case 'MUSIC1'
            data.music_order = ts.run_music_order(4,:);
        case 'CAPS1'
            data.music_order = ts.caps_music_order(1,:);
        case 'CAPS2'
            data.music_order = ts.caps_music_order(2,:);
    end
end

temp_rating_types = {
    'cont_int', '현재 느껴지는 통증의 세기를 지속적으로 보고해 주십시오.'; ...
    'cont_int_vas', '현재 느껴지는 통증의 세기를 지속적으로 보고해 주십시오.'; ...
    'cont_int_vas_exp', '+'; ...
    'cont_threat_vas', '현재 들리는 내용이 자신에게 얼마나 안전 혹은 위협을 느끼게 하는지 지속적으로 보고해 주십시오.'; ...
    'cont_sound_volume', '음향 크기를 적절히 조절해 주십시오.';...
    'overall_familiarity', '방금 들었던 음악의 친숙함을 보고해 주십시오.';...
    'overall_familiarity_lms', '방금 들었던 음악의 친숙함을 보고해 주십시오.';...
    'overall_pleasure', '방금 들었던 음악의 전반적인 음악적 쾌감을 보고해 주십시오.';...
    'overall_sound', ''; ...
    'cont_pleasure_vas', '현재 느껴지는 음악적 쾌감을 지속적으로 보고해 주십시오.'; ...
    'cont_pleasure_lms', '현재 느껴지는 음악적 쾌감을 지속적으로 보고해 주십시오.'; ...
    'cont_avoidance','앞으로 이 경험을 피하고 싶은 정도를 지속적으로 보고해주세요.'; ...
    'cont_avoidance_vas','앞으로 이 경험을 피하고 싶은 정도를 지속적으로 보고해주세요.'; ...
    'cont_avoidance_exp', '앞으로 이 경험을 피하고 싶은 정도를 지속적으로 보고해주세요.';...
    'overall_int', '자극이 얼마나 강했나요?';...
    'overall_avoidance', '앞으로 이 경험을 피하고 싶은 정도를 보고해주세요.';...
    'overall_unpleasant', '본인이 경험한 불쾌함의 정도를 보고해주세요.'; ...
    'overall_aversive_ornot', '방금의 자극이 싫었나요?';...
    'overall_pain_ornot', '방금의 자극이 아팠나요?'; ...
    'overall_boredness', '방금 세션동안 얼마나 지겨우셨나요?'; ...
    'overall_alertness', '방금 세션동안 얼마나 졸리셨나요, 혹은 얼마나 정신이 또렷했나요?'; ...
    'overall_relaxed', '지금 얼마나 편안한 상태이신가요?';...
    'overall_attention', '방금 세션동안 자극에 얼마나 집중하셨나요?'; ...
    'overall_music_attention', '방금 세션동안 음악에 얼마나 집중하셨나요?'; ...
    'overall_resting_positive', '방금 세션동안 했던 생각이 주로 긍정적이었나요?'; ...
    'overall_resting_negative', '방금 세션동안 했던 생각이 주로 부정적이었나요?'; ...
    'overall_resting_myself', '방금 세션동안 했던 생각이 주로 나 자신에 대한 것이었나요?'; ...
    'overall_resting_others', '방금 세션동안 했던 생각이 주로 다른 사람들에 대한 것이었나요?'; ...
    'overall_resting_imagery', '방금 세션동안 했던 생각이 주로 생생한 이미지를 포함하고 있었나요?';...
    'overall_resting_present', '방금 세션동안 했던 생각이 주로 지금, 여기에 대한 것이었나요?';...
    'overall_resting_past',  '방금 세션동안 주로 했던 생각이 과거에 대한 것이었나요?';...
    'overall_resting_future', '방금 세션동안 주로 했던 생각이 미래에 대한 것이었나요?';...
    'overall_resting_capsai_int', '방금 세션동안 경험했던 혀의 통증은 가장 심했을 때 얼마나 강했나요?';...
    'overall_resting_capsai_unp', '방금 세션동안 경험했던 혀의 통증은 가장 심했을 때 얼마나 불쾌했나요?';...
    'overall_negaud_int', '방금 세션동안 경험했던 소리자극은 가장 심했을 때 얼마나 강했나요?';...
    'overall_negaud_unp', '방금 세션동안 경험했던 소리자극은 가장 심했을 때 얼마나 불쾌했나요?';...
    'overall_posvis_int', '방금 세션동안 경험했던 시각자극은 가장 좋았을 때 얼마나 강했나요?';...
    'overall_posvis_ple', '방금 세션동안 경험했던 시각자극은 가장 좋았을 때 얼마나 기분이 좋았나요?';...
    'overall_mood', '방금 세션동안 기분은 어땠나요?';...
    'overall_comfortness', '지금 얼마나 편안한가요?';...
    'overall_music_pleasure_1', sprintf('1. <%s>의\n 전반적인 음악적 쾌감을 평가해주세요.',music_all.list{data.music_order(1)});...
    'overall_music_pleasure_2', sprintf('2. <%s>의\n 전반적인 음악적 쾌감을 평가해주세요.',music_all.list{data.music_order(2)});...
    'overall_music_pleasure_3', sprintf('3. <%s>의\n 전반적인 음악적 쾌감을 평가해주세요.',music_all.list{data.music_order(3)});...
    'overall_music_pleasure_4', sprintf('4. <%s>의\n 전반적인 음악적 쾌감을 평가해주세요.',music_all.list{data.music_order(4)});...
    'overall_music_attention_1', sprintf('1. <%s>의\n 전반적인 집중도를 평가해주세요.',music_all.list{data.music_order(1)});...
    'overall_music_attention_2', sprintf('2. <%s>의\n 전반적인 집중도를 평가해주세요.',music_all.list{data.music_order(2)});...
    'overall_music_attention_3', sprintf('3. <%s>의\n 전반적인 집중도를 평가해주세요.',music_all.list{data.music_order(3)});...
    'overall_music_attention_4', sprintf('4. <%s>의\n 전반적인 집중도를 평가해주세요.',music_all.list{data.music_order(4)});...
    'overall_music_familiarity_1', sprintf('1. <%s>의\n 전반적인 음악적 친숙함을 평가해주세요.',music_all.list{data.music_order(1)});...
    'overall_music_familiarity_2', sprintf('2. <%s>의\n 전반적인 음악적 친숙함을 평가해주세요.',music_all.list{data.music_order(2)});...
    'overall_music_familiarity_3', sprintf('3. <%s>의\n 전반적인 음악적 친숙함을 평가해주세요.',music_all.list{data.music_order(3)});...
    'overall_music_familiarity_4', sprintf('4. <%s>의\n 전반적인 음악적 친숙함을 평가해주세요.',music_all.list{data.music_order(4)});...
    'overall_music_chill_1', sprintf('1. <%s>에서\n 음악적 전율을 경험하셨나요?',music_all.list{data.music_order(1)}); ...
    'overall_music_chill_2', sprintf('2. <%s>에서\n 음악적 전율을 경험하셨나요?',music_all.list{data.music_order(2)}); ...
    'overall_music_chill_3', sprintf('3. <%s>에서\n 음악적 전율을 경험하셨나요?',music_all.list{data.music_order(3)}); ...
    'overall_music_chill_4', sprintf('4. <%s>에서\n 음악적 전율을 경험하셨나요?',music_all.list{data.music_order(4)}); ...
    };
rating_types.alltypes = temp_rating_types(:,1);
rating_types.prompts = temp_rating_types(:,2);

% string to double
for i = 1:numel(rating_types.prompts)
    rating_types.prompts{i} = double(rating_types.prompts{i});
end

rating_types.postallstims = {'REST1', 'TEST1', 'MUSIC1', 'CAPS1', 'CAPS2'};
for i  = 1:numel(rating_types.postallstims)
    rating_types.postalltypes{i} = [];
end

rating_types.postalltypes{1} = ...
    {'overall_relaxed', ...
    'overall_boredness', ...
    'overall_alertness'};

rating_types.postalltypes{2} = ...
    {'overall_relaxed', ...
    'overall_boredness', ...
    'overall_alertness'};

rating_types.postalltypes{3} = ...
    {'overall_relaxed', ...
    'overall_boredness', ...
    'overall_alertness', ...
    'overall_music_attention',...
    'overall_music_pleasure_1', ...
    'overall_music_attention_1', ...
    'overall_music_familiarity_1', ...
    'overall_music_chill_1', ...
    'overall_music_pleasure_2', ...
    'overall_music_attention_2', ...
    'overall_music_familiarity_2', ...
    'overall_music_chill_2', ...
    'overall_music_pleasure_3', ...
    'overall_music_attention_3', ...
    'overall_music_familiarity_3', ...
    'overall_music_chill_3', ...
    'overall_music_pleasure_4', ...
    'overall_music_attention_4', ...
    'overall_music_familiarity_4', ...
    'overall_music_chill_4'};

for i = [4 5]
    rating_types.postalltypes{i} = ...
        {'overall_relaxed', ...
        'overall_attention',...
        'overall_boredness', ...
        'overall_alertness', ...
        'overall_music_pleasure_1', ...
        'overall_music_attention_1', ...
        'overall_music_familiarity_1', ...
        'overall_music_chill_1', ...
        'overall_music_pleasure_2', ...
        'overall_music_attention_2', ...
        'overall_music_familiarity_2', ...
        'overall_music_chill_2', ...
        'overall_music_pleasure_3', ...
        'overall_music_attention_3', ...
        'overall_music_familiarity_3', ...
        'overall_music_chill_3', ...
        'overall_music_pleasure_4', ...
        'overall_music_attention_4', ...
        'overall_music_familiarity_4', ...
        'overall_music_chill_4'};
end

end


